### ISSUE TITLE
TransformerDiscoveryService not recognized

### ISSUE THREAD

**Issue by Chaos02** [McModLauncher/modlauncher#99] opened 2022-03-01 15:37 UTC
I believe that there is an error in the following line:
https://github.com/McModLauncher/modlauncher/blob/9b69c82a176c0896b264ab167813a52adc6f12cb/src/main/java/cpw/mods/modlauncher/TransformationServicesHandler.java#L122
I am trying to provide a `TransformerDiscoveryService` via a mod file in the /mods folder from Forge but my Service isn't recognized and never even constructed.
I have also seen an open issue which mentions something similiar being broken since 1.18 which is why I decided to open my own.
If this method is never meant to load files from the /mods folder, can this please be implemented or can I be pointed on how to hook into modlauncher? A person from the Forge team pointed out to me that this might be a problem at the modlauncher GitHub: [Original Thread](https://github.com/MinecraftForge/MinecraftForge/issues/8467)
([Source](https://github.com/Chaos02/SubFolderLoader/tree/787f575303a2a9d5b988b4938669203f68f67459))
([debug.log](https://pastebin.com/vB5UHcAk))

I cannot work further on my mod until this issue is ironed out - awaiting help soon :)

**Comment by noeppi-noeppi** [comment] 2022-03-01 17:45
I don't think `ITransformerDiscoveryService` is meant to be provided by mods. From my understanding, because of the way, the module layers are constructed, this is not even possible. Or at least is not possible if there wasn't another layer for services that can locate `ITransformerDiscoveryService`s.

For your specific problem: Have you tried adding a single `ITransformationService` that merges all the `ITransformationService`s from the subfolders and passes all the methods on to all of them?

**Comment by OrionDevelopment** [comment] 2022-03-01 18:07
> I am trying to provide a `TransformerDiscoveryService` via a mod file in the /mods folder from Forge but my Service isn't recognized and never even constructed.

This is by design not supported.
Mods and Plugings (Like `TransformerDiscoveryService`) are not supported from the same jar.

**Comment by Chaos02** [comment] 2022-03-01 18:12
how about only plugins?

> > I am trying to provide a `TransformerDiscoveryService` via a mod file in the /mods folder from Forge but my Service isn't recognized and never even constructed.
> 
> This is by design not supported. Mods and Plugings (Like `TransformerDiscoveryService`) are not supported from the same jar.

**Comment by cpw** [comment] 2022-03-06 19:35
Closing. This is not a bug with modlauncher, it's a design choice.

**Closed by cpw** 2022-03-06 19:35 UTC
